import Head from "next/head";

import Header from "../../components/Header";
import Project from "../../components/Project";
import Contact from "../../components/Contact";

const content = [
  {
    sectionTitle: "Deal Driver",
    sectionSubTitle: "A lean web app for helping sales teams meet efficiently",
    sectionContent: (
      <div>
        <p>
          A former VP of Sales at Benefitfocus reached out to me when he started
          his new consulting company looking to add some software to help guide
          not only his sales meeting with clients but also his client's meetings
          with their teams.
        </p>
        <p>
          One of my earliest jobs was designing sales presentations and software
          demos for use in sales presentations, so I had experience working with
          salespeople before and knew the importance of facilitating effective
          meetings.
        </p>
        <p>That's where Deal Driver comes in.</p>
      </div>
    ),
  },
  {
    sectionTitle: "Deal Driver 2",
    sectionSubTitle: "",
    sectionContent: (
      <div>
        <p>
          A former VP of Sales at Benefitfocus reached out to me when he started
          his new consulting company looking to add some software to help guide
          not only his sales meeting with clients but also his client's meetings
          with their teams.
        </p>
        <p>
          One of my earliest jobs was designing sales presentations and software
          demos for use in sales presentations, so I had experience working with
          salespeople before and knew the importance of facilitating effective
          meetings.
        </p>
        <p>That's where Deal Driver comes in.</p>
      </div>
    ),
  },
];

export default function TestPage() {
  return (
    <>
      {console.log("deal-driver.js:", content)}
      <Head>
        <title>Projects: Deal Driver</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header separated />
      <Project
        image={`projects/deal-driver/project-title.svg`}
        content={content}
      />

      <Contact />
    </>
  );
}
