import Head from "next/head";

import Header from "../components/Header";
import MainTitle from "../components/MainTitle";
import HireMe from "../components/HireMe";
import RecentWork from "../components/RecentWork";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <>
      <Head>
        {/* <!-- Google tag (gtag.js) --> */}
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-0K6VSCXSDN"
        ></script>
        <script>
          window.dataLayer = window.dataLayer || []; function gtag()
          {dataLayer.push(arguments)}
          gtag('js', new Date()); gtag('config', 'G-0K6VSCXSDN');
        </script>

        <title>Matt Coddington | UX/UI Designer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <MainTitle />
      <HireMe />
      <RecentWork />
      <Contact />
    </>
  );
}
