import Head from "next/head";

import Header from "../components/Header";
import MainTitle from "../components/MainTitle";
import HireMe from "../components/HireMe";
import RecentWork from "../components/RecentWork";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <MainTitle />
      <HireMe />
      <RecentWork />
      <Contact />
    </>
  );
}
